In [1]:
1+2

3

In [2]:
5-3

2

In [3]:
7*4

28

In [4]:
print(7*4)

28


In [5]:
abs(-19)

19

In [6]:
round(2.48)

2

In [7]:
round(2.485, 2)

2.48

In [8]:
# input function

name=input("Enter your name")
print(name)

Enter your namebipin
bipin


In [9]:
a=input("Enter 1st number")
b=input("Enter 2nd number")
c=a+b
print(c)

Enter 1st number3
Enter 2nd number2
32


In [10]:
type(b)

str

In [11]:
a=int(input("Enter 1st number"))
b=int(input("Enter 2nd number"))
c=a+b
print(c)

Enter 1st number2
Enter 2nd number6
8


In [12]:
type(b)

int

# Datatypes in Python

## Numerics types: int, float, complex

In [13]:
x = 5
print(x)
type(x)

5


int

In [14]:
x = 1.5
print(x)
type(x)

1.5


float

In [15]:
x = 2
y= 1+2j
print(x)
print(y)
print(type(x))
print(type(y))

2
(1+2j)
<class 'int'>
<class 'complex'>


## Boolean type: bool

In [16]:
d = True
print(d)
print(type(d))

True
<class 'bool'>


## Character type

In [17]:
a='hello...'
print(a)
print(type(a))

hello...
<class 'str'>


In [18]:
str1='c'
print(str1)
print(type(str1))

c
<class 'str'>


In [19]:
str2=('Hello world')
print(str2)

Hello world


In [20]:
# index of letter in string. eg: index of letter l in HelloWorld
str2.index('r')

8

In [21]:
str2[7]

'o'

In [22]:
str2[-2]

'l'

In [23]:
str2[2:7]

'llo w'

In [24]:
str2[-6:-2]

' wor'

In [25]:
print('my name is bipin')

my name is bipin


In [26]:
x=2
print(f'my age is {x}')

my age is 2


In [27]:
x = "Hello"  #concatenation
y = "World"
z = x + y
print(z)

HelloWorld


### sequence type
* list
* tuple
* dictionalry

### List:  
* Ordered, Mutable and allow duplicates
* Collection of heterogeneous data types

In [28]:
listExample = ["apple", "banana", "cherry", 2]

In [29]:
listExample


['apple', 'banana', 'cherry', 2]

In [30]:
listExample.index("banana")

1

In [31]:
listExample[2]

'cherry'

In [32]:
listExample[1:]

['banana', 'cherry', 2]

In [33]:
listExample[-1]

2

In [34]:
listExample[1:3]

['banana', 'cherry']

In [35]:
listExample[:3]

['apple', 'banana', 'cherry']

In [36]:
listExample[1]

'banana'

In [37]:
#list is mutable eg: banana is replaced with Mango
listExample[1]='Mango'
print(listExample)

['apple', 'Mango', 'cherry', 2]


In [38]:
# loop through list
for x in listExample:
  print(x)

apple
Mango
cherry
2


In [39]:
# check if item is in list
if "apple" in listExample:
  print("Yes, 'apple' is present in list")

Yes, 'apple' is present in list


In [40]:
len(listExample)

4

In [41]:
listExample.pop()
print(listExample)

['apple', 'Mango', 'cherry']


In [42]:
listExample.pop(2)    # The value at index is popped out and removed
print(listExample)

['apple', 'Mango']


### Tuple: Ordered, Immutable and allow duplicates

In [43]:
t = ('a','b',1,2)
print(t)

('a', 'b', 1, 2)


In [44]:
tup = 1,2,'a','c'
print(tup)

(1, 2, 'a', 'c')


In [46]:
#tuple is immutable
t[2]='c'

TypeError: 'tuple' object does not support item assignment

### Range

In [47]:
# create sequence of numbers from 2 to 7
x = range(2, 8)
for n in x:
  print(n)

2
3
4
5
6
7


In [48]:
# range(start, stop, step)
# create sequence of numbers from 2 to 9 but increment by 2 instead of 1

x= range(2,10,2)
for n in x:
  print(n)

2
4
6
8


### dictionary: unordered, changeable, indexed and key-value pair is used

In [49]:
d={10:'madhav', 11:'ajay', 12:'praveen'}
print(d)

{10: 'madhav', 11: 'ajay', 12: 'praveen'}


In [50]:
print(d.keys())

dict_keys([10, 11, 12])


In [51]:
print(d.values())

dict_values(['madhav', 'ajay', 'praveen'])


# Control Structures

## If ... else

In [52]:
a = 101
b = 100
if b > a:
    print("b is greater than a")

else:          
    print("a is greater than b")

a is greater than b


In [53]:
a = 101
b = 100
if b > a:
    print("b is greater than a")

elif (a > b):   # elif means if the previous conditions were not true, then try this condition.
    print("a is greater than b")


else:           # keyword catches anything which isn't caught by the preceding conditions
    print("a is equal to b")

a is greater than b


## Loops: for, while

In [54]:
# for loop
mylist=['x','y',1,2,3]
for i in mylist:
    print(i)

x
y
1
2
3


In [55]:
# while loop
i = 1
while i < 5:
    print(i)
    i=i+1


1
2
3
4


# Functions in Python

In [56]:
#Defining a function
def printme(str):

    print (str)

    return

In [57]:
#Calling function
printme("This is first call to the user defined function!")

This is first call to the user defined function!


In [58]:
def sum(a,b):
    c= a+b
    return c


In [59]:
sum(2,2)

4

In [60]:
def sum1(a,b):
    c= a+b
    print(c)

In [61]:
sum1(4,2)

6


In [62]:
y = lambda a,b: a**2 + b**2 + 2*a*b
y(2,4)


36

## Introduction to Numpy

* It stands for Numerical Python
* It is a fundamental package for numerical computations
* It supports N-dimensional array objects that can be used for processing multidimensional data

In [63]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [64]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

[1 2 3 4 5 6]


In [65]:
# ndim returns an integer which tell the number of dimensions that array have.

import numpy as np

p = np.array(50)
print(p.ndim)

q = np.array([1, 2, 3, 4, 5])
print(q.ndim)

r = np.array([[1, 2, 3], [4, 5, 6]])
print(r.ndim)

s = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(s.ndim)

0
1
2
3


In [66]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

print(arr1[0])

1


In [67]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

arr2[0, 1]

2

In [68]:
list1= [1,2,3,4]
arrl=np.array(list1)
print(arrl)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [69]:
import numpy as np
x = np.random.randint(100, size=[5,5]),
print(x)

(array([[71, 36, 87, 50, 86],
       [19, 73, 20, 97, 12],
       [67, 33,  6, 43, 24],
       [17, 90, 10, 17, 49],
       [22, 55, 12, 75, 78]]),)
